#!/usr/bin/env python3
"""make_si_figs.py : Supplementary Figs S7-S14 -> sections/si_figs.tex (round 7 to 9, 5 October 2026).

The figure agent draws these figures under outputs/figures/paper/v3_restructure/si/ as FigS<file>.pdf (and .png) with the
legend FigS<file>_legend.md. The planned S13 (prediction maps of the independent regions) cannot be drawn, because no
gridded prediction exists for Central Russia or the Tibetan Plateau; it was dropped in round 9 and the later figures moved
up (display S13 = file FigS14, display S14 = file FigS15). Display numbers follow first citation: S7 is cited in
Supplementary Note 2, S8 to S14 only in the opening sentence of this block.
For each display number:
  * PDF and a trimmed caption (tools/si_fig_captions.py) present: the figure is placed with the trimmed caption, which keeps
    every number and flag of the legend file (checked by si_fig_captions.check);
  * PDF and legend present but no trimmed caption: the legend file is converted (headings and HTML comments removed, bold
    and italics converted, LaTeX specials escaped; numbers unchanged, no renumbering);
  * PDF present, legend missing: the planned caption with a blue [SI legend: to be written] marker;
  * nothing present: the placeholder box with the planned caption.
The opening sentence (sections/si_figs_lead.tex, read into the first paragraph of the Supplementary Figures so that it does not
stand alone on a page) names the figures and any that are incomplete.
Re-run whenever files in the si folder change, then ./build.sh si_main.
Usage: python3 tools/make_si_figs.py   (run from paper/manuscript/en)
"""
import glob
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import si_fig_captions as SC  # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SI = os.path.join(ROOT, "outputs", "figures", "paper", "v3_restructure", "si")
REL = "../../../outputs/figures/paper/v3_restructure/si"
OUT = os.path.join(HERE, "sections", "si_figs.tex")
LEAD = os.path.join(HERE, "sections", "si_figs_lead.tex")   # sentence read into the opening paragraph of the Supplementary Figures

FILE = {7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 14, 14: 15}   # display number -> file number
TBD = "\\textcolor{blue}{[SI figure: to be drawn]}"
PLAN = {  # display number -> planned caption (used only while a figure or its legend is missing)
    7: "Scoring-scheme comparison in Alaska (M1, six folds; Supplementary Note 2). Split maps and distance distributions for each scoring scheme (test-to-training and prediction-grid-to-label distances, as in Meyer and Pebesma 2022).",
    8: "Transfer without target labels. Target-wise maps of the error change of the low-weight residual and of the anchor plus residual relative to the source-coefficient model; learner-wise detail.",
    9: "Coefficient recalibration. Target-wise maps of the source-coefficient error and of the ten-label recalibration gain; curves of the soil-property recalibrated Stefan model; regional contrast forest plots.",
    10: "Method selection. Target-wise maps of the method selected by the rule and of the rule minus the fixed recipe; matrix and rank scatter of the source cross-validation tuning.",
    11: "Gains within label-rich regions. Maps of the error change by scoring block in the Lena Delta and Canada; figures of XE, XI and XB.",
    12: "Placement of new labels. Target-wise maps of strategy minus random cells; proximity and distance contrasts (L23, L24); learned placement policy (XD).",
    13: "Prediction intervals. Maps of predicted ALT, 90\\% interval width and the extrapolation area for the Lena Delta (outputs/maps/transfer\\_lena/).",
    14: "Deployment scenarios. Scenario matrix, stopping-rule curves and forest plot of the abstract contrast bundle (panels moved from an earlier draft of the main figures).",
}


def esc(s):
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_"), ("$", "\\$"), ("~", "\\textasciitilde{}")):
        s = s.replace(a, b)
    return s


def legend_file(fnum):
    for pat in (f"FigS{fnum}_legend.md", f"FigS{fnum}_legend_en.md", f"FigS{fnum}.md"):
        hits = sorted(glob.glob(os.path.join(SI, pat)))
        if hits:
            return hits[0]
    return None


def caption_from(md):
    body = SC.visible(open(md, encoding="utf-8").read())
    body = esc(body)
    body = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", body)
    body = re.sub(r"(?<![\*\w])\*(?!\s)(.+?)(?<!\s)\*(?![\*\w])", r"\\textit{\1}", body)
    return body


def fmt_list(nums):
    s = ["S%d" % n for n in nums]
    return s[0] if len(s) == 1 else ", ".join(s[:-1]) + " and " + s[-1]


def main():
    out = ["% si_figs.tex : generated by tools/make_si_figs.py (do not edit by hand).",
           "% Supplementary Figs S7-S14; files outputs/figures/paper/v3_restructure/si/FigS<file>.pdf (S13 = file FigS14, S14 = file FigS15);"
           " captions from tools/si_fig_captions.py (trimmed legends)."]
    status, missing = [], []
    for n in sorted(FILE):
        f = FILE[n]
        pdf = os.path.join(SI, f"FigS{f}.pdf")
        md = legend_file(f)
        if os.path.exists(pdf):
            stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(os.path.getmtime(pdf)))
            if n in SC.CAPTIONS and md:
                cap, src = SC.CAPTIONS[n][2], f"trimmed caption of {os.path.basename(md)} ({SC.words(SC.CAPTIONS[n][2])} words)"
                status.append((n, f"placed (file FigS{f}), trimmed caption, {SC.words(cap)} words"))
            elif md:
                cap, src = caption_from(md), f"caption converted from {os.path.basename(md)}"
                status.append((n, f"placed (file FigS{f}), legend converted"))
            else:
                cap = PLAN[n] + " \\textcolor{blue}{[SI legend: to be written]}"
                src = "legend file not found; planned caption"
                missing.append(n)
                status.append((n, f"placed (file FigS{f}), legend missing"))
            out.append(f"% S{n}: FigS{f}.pdf (file time {stamp}); {src}")
            out.append("\\begin{figure}[p]\\centering")
            out.append(f"\\includegraphics[width=\\linewidth,height=0.72\\textheight,keepaspectratio]{{{REL}/FigS{f}.pdf}}")
            out.append(f"\\caption{{{cap}}}\\label{{figsi:S{n}}}")
            out.append("\\end{figure}")
            out.append("\\clearpage")
        else:
            missing.append(n)
            status.append((n, "placeholder"))
            out.append(f"% S{n}: placeholder (FigS{f}.pdf not found)")
            out.append("\\begin{figure}[htbp]\\centering")
            out.append(f"\\fbox{{\\parbox[c][45mm][c]{{0.85\\linewidth}}{{\\centering Supplementary Fig.~S{n} in preparation}}}}")
            out.append(f"\\caption{{{PLAN[n]} {TBD}}}\\label{{figsi:S{n}}}")
            out.append("\\end{figure}")
            out.append("")
    first, last = min(FILE), max(FILE)
    if not missing:
        lead = (f"Supplementary Fig.~S{first} shows the scoring-scheme comparison of Supplementary Note 2, and Supplementary Figs~S{first + 1} to S{last} "
                "show result maps and panels moved out of the main figures.")
    else:
        word = "Fig.~" if len(missing) == 1 else "Figs~"
        verb = "is incomplete" if len(missing) == 1 else "are incomplete"
        lead = (f"Supplementary Figs~S{first} to S{last} show the scoring-scheme comparison of Supplementary Note 2 and result maps and panels moved out "
                f"of the main figures; Supplementary {word}{fmt_list(missing)} {verb}.")
    open(LEAD, "w", encoding="utf-8").write("% si_figs_lead.tex : generated by tools/make_si_figs.py\n" + lead + "%\n")
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote", OUT)
    for n, st in status:
        print(f"  S{n}: {st}")
    probs = SC.check(SI)
    print("caption check:", "ok" if not probs else "")
    for p in probs:
        print("  WARNING", p)


if __name__ == "__main__":
    main()
