#!/usr/bin/env python3
"""make_si_maps.py : Supplementary Figs S10-S15 (1 km ALT maps and the XK/XL figures) -> sections/si_maps.tex.

Figures and captions: outputs/figures/paper/v3_restructure/maps/<name>.pdf and <name>_legend.md (round 3,
5 October 2026). The caption is the legend file with the Markdown heading removed, bold converted, LaTeX
specials escaped and references to other map figures replaced by Supplementary Figure numbers. Numbers are
copied unchanged. Re-run after the map files change; the build reads the PDF at compile time.
Usage: python3 tools/make_si_maps.py   (run from paper/manuscript/en)
"""
import os
import re

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
MAPS = os.path.join(ROOT, "outputs", "figures", "paper", "v3_restructure", "maps")
REL = "../../../outputs/figures/paper/v3_restructure/maps"
OUT = os.path.join(HERE, "sections", "si_maps.tex")

FIGS = [  # (number, file stem)
    (10, "Alaska_ALT_map_v3"),
    (11, "Lena_ALT_map_v3"),
    (12, "XL_display_resolution"),
    (13, "XL_Alaska_product_differences"),
    (14, "XL_Lena_product_differences"),
    (15, "XK_support_scale"),
]
REFS = [  # internal wording of the legend files -> Supplementary Figure numbers (no numbers change)
    ("(finding C8)", "(main text, Fig.~7c)"),
    ("as in the Alaska map figure", "as in Supplementary Fig.~S10"),
    ("as in the Lena map figure", "as in Supplementary Fig.~S11"),
    ("the scale of the correction panel of the map figure with the sign reversed", "the scale of panel b of Supplementary Figs~S10 and S11 with the sign reversed"),
    ("(product comparison table and the support-scale figure)", "(Supplementary Table S13 and Supplementary Fig.~S15)"),
    ("Projections as in the map figures", "Projections as in Supplementary Figs~S10 and S11"),
    ("Data as in the map figures", "Data as in Supplementary Figs~S10 and S11"),
    ("narrower than in the map figures", "narrower than in Supplementary Figs~S10 and S11"),
    ("(source table)", "(data/processed/xbatch/XK\\_support\\_scale/)"),
]


def esc(s):
    for a, b in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_"), ("$", "\\$"), ("~", "\\textasciitilde{}")):
        s = s.replace(a, b)
    return s


def caption(stem):
    lines = [ln.rstrip() for ln in open(os.path.join(MAPS, stem + "_legend.md"), encoding="utf-8")]
    body = " ".join(ln for ln in lines if ln and not ln.startswith("#"))
    body = esc(body)
    body = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", body)
    for a, b in REFS:
        body = body.replace(esc(a) if "\\" not in a else a, b)
    return body


def main():
    out = ["% si_maps.tex : generated by tools/make_si_maps.py (do not edit by hand).",
           "% Supplementary Figs S10-S15: 1 km ALT maps (display resolution, no accuracy claim) and the XK/XL figures."]
    for num, stem in FIGS:
        pdf = f"{REL}/{stem}.pdf"
        mt = os.path.getmtime(os.path.join(MAPS, stem + ".pdf"))
        import time
        stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(mt))
        out.append(f"% S{num}: {stem}.pdf (file time {stamp}); caption from {stem}_legend.md")
        out.append("\\begin{figure}[p]\\centering")
        out.append(f"\\IfFileExists{{{pdf}}}{{\\includegraphics[width=\\linewidth,height=0.72\\textheight,keepaspectratio]{{{pdf}}}}}"
                   f"{{\\fbox{{\\parbox[c][45mm][c]{{0.85\\linewidth}}{{\\centering Supplementary Fig.~S{num} in preparation}}}}}}")
        out.append(f"\\caption{{{caption(stem)}}}\\label{{fig:S{num}}}")
        out.append("\\end{figure}")
        out.append("\\clearpage")
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
